FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
LABEL maintainer="PeteGrady" version="0.1" name="weather_api"
# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -v diag -c Release -o out

EXPOSE 1971

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y curl
HEALTHCHECK CMD curl --fail http://localhost:1971/ || exit 1
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "WeatherAPI.dll"]
