## https://vsupalov.com/docker-arg-env-variable-guide/
version: '3.4'
services:
    timer:
        build:
            context: ../timer/timer-demo
            dockerfile: dockerfile
            args:
                build-type: build-prod
        networks:
        - main
        ports:
        - '5050:80'
        restart: unless-stopped
    api:
        build:
            context: ../weather_api/WeatherAPI
            dockerfile: dockerfile
        networks:
        - main
        ports:
         - '1971:1971'
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
        restart: unless-stopped
networks:
  main:
    driver: bridge

