## https://vsupalov.com/docker-arg-env-variable-guide/
version: '2.4'
services:
  mem_limit: 30m
  timer:
    build:
      context: ../timer/timer-demo
      dockerfile: timer.dockerfile
    networks:
      - home_page
    ports:
      - '3337:80'
    restart: unless-stopped
  weather_api:
    mem_limit: 70m
    build:
      context: ../weather_api/WeatherAPI
      dockerfile: dockerfile
    networks:
      - home_page
    ports:
      - '1971:1971'
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - timer
    restart: unless-stopped
networks:
  home_page:
    driver: bridge
