## https://vsupalov.com/docker-arg-env-variable-guide/
version: '3.4'
services:
  timer:
    build:
      context: ../timer/timer-demo
      dockerfile: timer.dockerfile
    networks:
      - home_page
    ports:
      - '5050:80'
    restart: unless-stopped
  weather_api:
    build:
      context: ../weather_api/WeatherAPI
      dockerfile: dockerfile
    networks:
      - home_page
    ports:
      - '1971:5000'
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - timer
    restart: unless-stopped
networks:
  home_page:
    driver: bridge
